service: mediabox-storage-profile

custom:
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  profileTable: ${self:custom.stage}-profile
  backupEnabled:
    dev: false
    stage: false
    prod: true

provider:
  name: aws
  stage: dev
  region: ${opt:region,'us-east-1'}
  profile: ${opt:profile, 'prodhta'}

resources:
  Resources:
    #Profile Table Config
    ProfileTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: ${self:custom.profileTable}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: ${self:custom.backupEnabled.${opt:stage, self:provider.stage}}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
  Outputs:
    ProfileTableArn:
      Value:
        Fn::GetAtt:
          - ProfileTable
          - Arn
      Export:
        Name: ${self:custom.stage}-ProfileTableArn
