/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsconfig_dev = {
    aws_project_region: "ap-south-1",
    aws_cognito_region: "ap-south-1",
    aws_user_pools_id: "ap-south-1_2wwb3RO57",
    aws_user_pools_web_client_id: "7kj0hptsuilrinhg5cau6rt60b",
    oauth: {
      domain: "dev-hta.auth.ap-south-1.amazoncognito.com",
      scope: ["email", "openid", "profile"],
      redirectSignIn: "http://localhost:4200/auth/login",
      redirectSignOut: "http://localhost:4200",
      responseType: "code",
    },
    federationTarget: "COGNITO_USER_POOLS",
    cookieStorage: {
      domain: 'localhost',
      secure: false,
      path: '/',
      expires: 365,
    },
  };
  export default awsconfig_dev;
  